name: Deploy to ECR
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
        AWS_REGION: us-east-1

    - name: Debug ECR Registry
      run: echo "ECR_REGISTRY is $ECR_REGISTRY"
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}

    - name: Build, test, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: clo835-week3-1
        IMAGE_TAG: v0.1
      run: |
        cd Chapter02/kubia/
        ls -ltra
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG . --progress=plain
        docker run -d -p 80:8080 --name nodeapp $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG || (echo "Run failed"; docker logs nodeapp; exit 1)
        docker ps
        echo "Pause for 10 seconds to let container start"
        sleep 10
        curl localhost:80 -vvv || (echo "Curl failed"; exit 1)
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
